// <auto-generated />
using AlmacenMis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlmacenMis.Data.Migrations
{
    [DbContext(typeof(AlmacenMisDbContext))]
    [Migration("20260422215241_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlmacenMis.Dominio.Almacen", b =>
                {
                    b.Property<int>("almacen_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("almacen_id"));

                    b.Property<string>("Código")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("almacen_id");

                    b.ToTable("Almacen", (string)null);
                });

            modelBuilder.Entity("AlmacenMis.Dominio.Producto", b =>
                {
                    b.Property<int>("id_Producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_Producto"));

                    b.Property<string>("Código")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_Producto");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("AlmacenMis.Dominio.ProductoAlmacen", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("almacen_id")
                        .HasColumnType("integer");

                    b.Property<int>("producto_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("almacen_id");

                    b.HasIndex("producto_id");

                    b.ToTable("Producto_Almacen", (string)null);
                });

            modelBuilder.Entity("AlmacenMis.Dominio.ProductoProveedor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("producto_id")
                        .HasColumnType("integer");

                    b.Property<int>("proveedor_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("producto_id");

                    b.HasIndex("proveedor_id");

                    b.ToTable("Producto_Proveedor", (string)null);
                });

            modelBuilder.Entity("AlmacenMis.Dominio.ProductoProveedorAlmacen", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("almacen_id")
                        .HasColumnType("integer");

                    b.Property<int>("producto_id")
                        .HasColumnType("integer");

                    b.Property<int>("proveedor_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("almacen_id");

                    b.HasIndex("producto_id");

                    b.HasIndex("proveedor_id");

                    b.ToTable("Producto_Proveedor_Almacen", (string)null);
                });

            modelBuilder.Entity("AlmacenMis.Dominio.Proveedor", b =>
                {
                    b.Property<int>("id_proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_proveedor"));

                    b.Property<string>("Código")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_proveedor");

                    b.ToTable("Proveedor", (string)null);
                });

            modelBuilder.Entity("AlmacenMis.Dominio.Stock", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("almacen_id")
                        .HasColumnType("integer");

                    b.Property<int>("cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("producto_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("almacen_id");

                    b.HasIndex("producto_id");

                    b.ToTable("Stock", (string)null);
                });

            modelBuilder.Entity("AlmacenMis.Dominio.ProductoAlmacen", b =>
                {
                    b.HasOne("AlmacenMis.Dominio.Almacen", null)
                        .WithMany()
                        .HasForeignKey("almacen_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlmacenMis.Dominio.Producto", null)
                        .WithMany()
                        .HasForeignKey("producto_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlmacenMis.Dominio.ProductoProveedor", b =>
                {
                    b.HasOne("AlmacenMis.Dominio.Producto", null)
                        .WithMany()
                        .HasForeignKey("producto_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlmacenMis.Dominio.Proveedor", null)
                        .WithMany()
                        .HasForeignKey("proveedor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlmacenMis.Dominio.ProductoProveedorAlmacen", b =>
                {
                    b.HasOne("AlmacenMis.Dominio.Almacen", null)
                        .WithMany()
                        .HasForeignKey("almacen_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlmacenMis.Dominio.Producto", null)
                        .WithMany()
                        .HasForeignKey("producto_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlmacenMis.Dominio.Proveedor", null)
                        .WithMany()
                        .HasForeignKey("proveedor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlmacenMis.Dominio.Stock", b =>
                {
                    b.HasOne("AlmacenMis.Dominio.Almacen", null)
                        .WithMany()
                        .HasForeignKey("almacen_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlmacenMis.Dominio.Producto", null)
                        .WithMany()
                        .HasForeignKey("producto_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
